### ISSUE TITLE
Description of Themes im Anhang Eingabefelder

### ISSUE THREAD

**Issue by mzurki** [I14Y-ch/handbook#5]
The description states that the themes are based on the EU vocabulary which is not correct. The I14Y themes are based on the I14Y Themevocabulary also see here: https://www.i14y.admin.ch/de/concepts/08da58dc-4dc8-f9cb-b6f2-7d16b3fa0cde/description

**Comment by MathiasBornI14Y** [comment]
Thank you very much for pointing this out. It was indeed an error. In the meantime, the relevant text passage has been adjusted.

**Comment by MathiasBornI14Y** [comment]
The new version is published.
